server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample
    username: root
    password: Wardha
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


